services:
  db:
    image: mysql
    container_name: quiz_mysql_db

    env_file: .env

    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

